GET http://localhost:3000/article HTTP/1.1

###
POST http://localhost:3000/article
Content-Type: application/json

{
  "title": "House chores 3",
  "content": "Do laundry, Wash dishes1, Sweep the yard, Iron clothes",
  "author": "Me, you and them"
}



###
GET http://localhost:3000/article/1 HTTP/1.1


###
PATCH http://localhost:3000/article/1 HTTP/1.1
Content-Type: application/json

{
  "title": "House chores 1",
  "content": "Do laundry",
  "author": "Me"
}

###
DELETE http://localhost:3000/article/1 HTTP/1.1

